package gg.yetisboxxed.yetipl.listener;

import gg.yetisboxxed.yetipl.YetiPLPlugin;
import gg.yetisboxxed.yetipl.service.*;
import gg.yetisboxxed.yetipl.util.Msg;
import gg.yetisboxxed.yetipl.util.Format;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;
import org.bukkit.entity.TNTPrimed;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.*;
import org.bukkit.event.entity.EntityDamageByEntityEvent;
import org.bukkit.event.entity.EntityExplodeEvent;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.player.*;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;
import org.bukkit.util.Vector;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

@SuppressWarnings("deprecation")
public final class CoreListener implements Listener {
    private final YetiPLPlugin plugin;
    private final Map<UUID,Long> lastAttack=new ConcurrentHashMap<>();
    private final Map<UUID,Long> lastChat=new ConcurrentHashMap<>();
    private final Map<UUID,List<Location>> tpPads=new HashMap<>();
    private final Set<UUID> advancing=new HashSet<>();

    public CoreListener(YetiPLPlugin plugin){this.plugin=plugin;}

    @EventHandler public void onPreLogin(AsyncPlayerPreLoginEvent e){String player=plugin.bans().active(e.getUniqueId());String ip=plugin.bans().activeIp(e.getAddress().getHostAddress());String reason=player!=null?player:ip;if(reason!=null)e.disallow(AsyncPlayerPreLoginEvent.Result.KICK_BANNED,"✦ YETIBOXXED ✦\nTemporarily banned\n"+reason+"\nDiscord: "+plugin.rules().discord());}

    @EventHandler public void onJoin(PlayerJoinEvent e){Player p=e.getPlayer();e.joinMessage(Component.text("✦ YetiPL ✦ ➜ ",NamedTextColor.GOLD).append(Component.text(p.getName()+" joined the game",NamedTextColor.YELLOW)));if(!p.hasPlayedBefore()){p.sendTitle("§6WELCOME TO YETIBOXXED","§eEnjoy your first adventure!",10,80,20);p.playSound(p.getLocation(),Sound.ENTITY_PLAYER_LEVELUP,1f,1f);}plugin.resourcePack().send(p); Bukkit.getScheduler().runTaskLater(plugin,()->Bukkit.getOnlinePlayers().forEach(plugin.itemDisguises()::refresh),10L);}
    @EventHandler public void onQuit(PlayerQuitEvent e){Player p=e.getPlayer();e.quitMessage(plugin.moderation().vanished(p)?null:Component.text("✦ YetiPL ✦ ← ",NamedTextColor.GOLD).append(Component.text(p.getName()+" left the game",NamedTextColor.YELLOW)));if(p.getWorld()==plugin.presets().world())plugin.presets().leave(p);}

    @EventHandler public void onChangedWorld(PlayerChangedWorldEvent e){if(e.getFrom()==plugin.presets().world()&&e.getPlayer().getWorld()!=plugin.presets().world())plugin.presets().leave(e.getPlayer());}

    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void onMove(PlayerMoveEvent e){Player p=e.getPlayer();if(plugin.moderation().frozen(p.getUniqueId())&&e.getFrom().distanceSquared(e.getTo())>0.0001){e.setTo(e.getFrom());return;}if(p.getWorld()==plugin.presets().world()){UUID owner=plugin.presets().ownerAt(e.getTo());if(owner==null||!plugin.presets().canVisit(p,owner)){Location own=plugin.presets().center(p.getUniqueId());if(own!=null)e.setTo(own);return;}Block b=e.getTo().getBlock();if(b.getType()==Material.END_PORTAL_FRAME){List<Location> pads=tpPads.getOrDefault(owner,List.of());if(pads.size()==2){Location a=pads.get(0),c=pads.get(1);Location here=b.getLocation();if(here.equals(a))p.teleport(c.clone().add(0.5,1,0.5));else if(here.equals(c))p.teleport(a.clone().add(0.5,1,0.5));}}}
        Location dest=plugin.portals().destinationAt(e.getTo());if(dest!=null&&p.getCooldown(Material.ENDER_PEARL)==0){p.teleport(dest);p.setCooldown(Material.ENDER_PEARL,20);}}

    @EventHandler(ignoreCancelled=true) public void onWand(PlayerInteractEvent e){Player p=e.getPlayer();ItemStack hand=e.getItem();if(hand!=null&&plugin.isWand(hand)&&e.getClickedBlock()!=null){e.setCancelled(true);if(e.getAction()==org.bukkit.event.block.Action.LEFT_CLICK_BLOCK){plugin.selections().pos1(p,e.getClickedBlock().getLocation());p.sendMessage(Msg.gold("Position 1 set."));}else if(e.getAction()==org.bukkit.event.block.Action.RIGHT_CLICK_BLOCK){plugin.selections().pos2(p,e.getClickedBlock().getLocation());p.sendMessage(Msg.gold("Position 2 set."));}return;}if(e.getHand()!=EquipmentSlot.HAND)return;handleInteract(e);}

    private void handleInteract(PlayerInteractEvent e){Player p=e.getPlayer();ItemStack hand=p.getInventory().getItemInMainHand();if(e.getClickedBlock()!=null){String region=plugin.regions().at(e.getClickedBlock().getLocation());if(region!=null&&!p.hasPermission("yetipl.regions.bypass")){if(!plugin.regions().flag(region,"interact")){e.setCancelled(true);p.sendMessage(Msg.error("Interaction is disabled in "+region+"."));return;}if(plugin.regions().blockedHand(region,hand.getType())){e.setCancelled(true);p.sendMessage(Msg.error("That item is blocked in "+region+"."));return;}if(!plugin.regions().requiresHand(region,hand.getType())){e.setCancelled(true);p.sendMessage(Msg.error("You are not holding a required item for "+region+"."));return;}}}String id=plugin.customItems().id(hand);if(id!=null&&e.getAction().isRightClick()){if(!plugin.presets().insideOwn(p)){p.sendMessage(Msg.error("Custom shop items only work inside your own Preset."));e.setCancelled(true);return;}switch(id){case "throwable_tnt"->{e.setCancelled(true);TNTPrimed t=p.getWorld().spawn(p.getEyeLocation(),TNTPrimed.class);t.setFuseTicks(40);t.setVelocity(p.getLocation().getDirection().normalize().multiply(1.2));}case "nuke"->{e.setCancelled(true);if(plugin.lagProtector().blockExplosions()){p.sendMessage(Msg.error("Nukes are temporarily disabled by Lag Protector."));return;}Location at=p.getTargetBlockExact(40)!=null?p.getTargetBlockExact(40).getLocation():p.getLocation().add(p.getLocation().getDirection().multiply(8));Bukkit.getScheduler().runTaskLater(plugin,()->at.getWorld().createExplosion(at,8f,false,true,p),20L);}default->{}}}
        if(e.getClickedBlock()!=null){String crate=plugin.crates().at(e.getClickedBlock().getLocation());if(crate!=null){e.setCancelled(true);if(!plugin.crates().matchesKey(p,crate)){p.sendMessage(Msg.error("You need the bound key for this crate."));return;}ItemStack reward=plugin.crates().randomReward(crate);if(reward==null){p.sendMessage(Msg.error("This crate has no rewards configured."));return;}ItemStack key=p.getInventory().getItemInMainHand();key.setAmount(key.getAmount()-1);p.getInventory().addItem(reward);p.sendMessage(Msg.gold("Crate opened! You received "+reward.getType()+"."));return;}
            if(hand.getType()==Material.BRUSH&&(e.getClickedBlock().getType()==Material.SUSPICIOUS_SAND||e.getClickedBlock().getType()==Material.SUSPICIOUS_GRAVEL)){String arch=plugin.archaeology().at(e.getClickedBlock().getLocation());if(arch!=null){e.setCancelled(true);Block block=e.getClickedBlock();Material original=block.getType();ItemStack reward=plugin.archaeology().reward(arch);if(reward!=null)p.getWorld().dropItemNaturally(block.getLocation().add(.5,.7,.5),reward);block.setType(Material.AIR,false);Bukkit.getScheduler().runTaskLater(plugin,()->block.setType(original,false),plugin.archaeology().respawn(arch));return;}}
            String disc=plugin.discs().id(hand);if(disc!=null&&e.getClickedBlock().getType()==Material.JUKEBOX){e.setCancelled(true);String sound=plugin.discs().sound(disc);if(sound!=null)for(Player viewer:p.getWorld().getPlayers())viewer.playSound(e.getClickedBlock().getLocation(),sound,SoundCategory.RECORDS,1f,1f);}}
    }

    @EventHandler(ignoreCancelled=true) public void onPlace(BlockPlaceEvent e){Player p=e.getPlayer();if(p.getWorld()==plugin.presets().world()){UUID owner=plugin.presets().ownerAt(e.getBlock().getLocation());if(owner==null||!plugin.presets().canEdit(p,owner)){e.setCancelled(true);p.sendMessage(Msg.error("You cannot edit this Preset."));return;}Set<String> denied=Set.of("COMMAND_BLOCK","CHAIN_COMMAND_BLOCK","REPEATING_COMMAND_BLOCK","COMMAND_BLOCK_MINECART","STRUCTURE_VOID","TEST_BLOCK","TEST_INSTANCE_BLOCK");if(denied.contains(e.getBlock().getType().name())&&!p.hasPermission("yetipl.presets.restricteditems.bypass")){e.setCancelled(true);p.sendMessage(Msg.error("That technical block is disabled in Presets."));return;}if(plugin.customItems().tagged(e.getItemInHand(),"tp_pads")){List<Location> pads=tpPads.computeIfAbsent(owner,k->new ArrayList<>());if(pads.size()>=2)pads.clear();pads.add(e.getBlock().getLocation());p.sendMessage(Msg.gold("TP Pad "+(pads.size()==1?"A":"B")+" placed."));}}
        String r=plugin.regions().at(e.getBlock().getLocation());if(r!=null&&!plugin.regions().flag(r,"place")&&!p.hasPermission("yetipl.regions.bypass")){e.setCancelled(true);p.sendMessage(Msg.error("You can't place blocks in "+r+"."));}}

    @EventHandler(ignoreCancelled=true) public void onBreak(BlockBreakEvent e){Player p=e.getPlayer();if(p.getWorld()==plugin.presets().world()){UUID owner=plugin.presets().ownerAt(e.getBlock().getLocation());if(owner==null||!plugin.presets().canEdit(p,owner)){e.setCancelled(true);p.sendMessage(Msg.error("You cannot edit this Preset."));return;}}
        String r=plugin.regions().at(e.getBlock().getLocation());if(r!=null&&!plugin.regions().flag(r,"break")&&!p.hasPermission("yetipl.regions.bypass")){e.setCancelled(true);p.sendMessage(Msg.error("You can't break blocks in "+r+"."));return;}String gen=plugin.gens().at(e.getBlock().getLocation());if(gen!=null){Location l=e.getBlock().getLocation().clone();Bukkit.getScheduler().runTaskLater(plugin,()->l.getBlock().setType(plugin.gens().randomBlock(gen),false),plugin.gens().delay(gen));}}

    @EventHandler(ignoreCancelled=true) public void onBlockDamage(BlockDamageEvent e){if(plugin.customItems().tagged(e.getPlayer().getInventory().getItemInMainHand(),"insta_mine_pick")&&plugin.presets().insideOwn(e.getPlayer()))e.setInstaBreak(true);}

    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void onDamage(EntityDamageByEntityEvent e){if(!(e.getDamager() instanceof Player p))return;if(e.getEntity() instanceof Player target && !plugin.getConfig().getBoolean("pvp.allow-naked-killing",false) && Arrays.stream(target.getInventory().getArmorContents()).allMatch(i->i==null||i.getType().isAir())){e.setCancelled(true);p.sendMessage(Msg.error("Naked killing is disabled."));return;}if(plugin.moderation().frozen(p.getUniqueId())){e.setCancelled(true);return;}long now=System.nanoTime();long last=lastAttack.getOrDefault(p.getUniqueId(),0L);long cd=plugin.getConfig().getLong("pvp.attack-cooldown-ms",600)*1_000_000L;if(now-last<cd&&!p.hasPermission("yetipl.pvp.cooldown.bypass")){e.setCancelled(true);return;}lastAttack.put(p.getUniqueId(),now);if(plugin.customItems().tagged(p.getInventory().getItemInMainHand(),"one_hit_sword")&&plugin.presets().insideOwn(p)){e.setDamage(1000000);}String r=plugin.regions().at(p.getLocation());if(r!=null&&!plugin.regions().flag(r,"pvp")&&e.getEntity() instanceof Player){e.setCancelled(true);p.sendMessage(Msg.error("PvP is disabled in "+r+"."));}}

    @EventHandler(ignoreCancelled=true) public void onExplosion(EntityExplodeEvent e){if(plugin.lagProtector().blockExplosions())e.setCancelled(true);}

    @EventHandler(priority=EventPriority.HIGHEST) public void onChat(AsyncPlayerChatEvent e){Player p=e.getPlayer();if(plugin.chatGames().submit(p,e.getMessage())){e.setCancelled(true);return;}if(plugin.moderation().frozen(p.getUniqueId())&&plugin.getConfig().getBoolean("freeze.block-chat",false)){e.setCancelled(true);return;}long now=System.nanoTime();double seconds=plugin.ranks().cooldown(p);long wait=(long)(seconds*1_000_000_000L);long previous=lastChat.getOrDefault(p.getUniqueId(),0L);if(now-previous<wait){e.setCancelled(true);double remain=(wait-(now-previous))/1_000_000_000.0;p.sendMessage(Msg.error("Please wait "+String.format(Locale.US,"%.2f",remain)+"s before chatting again."));return;}ChatFilterService.Result filtered=plugin.chatFilter().apply(e.getMessage());if(filtered.blocked()&&!p.hasPermission("yetipl.chatfilter.bypass")){e.setCancelled(true);p.sendMessage(Msg.error("That message was blocked by the chat filter."));return;}e.setMessage(filtered.message());String prefix=Format.formatSafe(plugin.ranks().prefix(p.getUniqueId()));String suffix=Format.formatSafe(plugin.ranks().suffix(p.getUniqueId()));String color=Format.formatSafe(plugin.ranks().chatColor(p.getUniqueId()));e.setFormat(prefix+(prefix.isBlank()?"":" ")+"%1$s"+suffix+" §7» "+color+"%2$s");lastChat.put(p.getUniqueId(),now);String lower=e.getMessage().toLowerCase(Locale.ROOT);for(Player target:Bukkit.getOnlinePlayers())if(!target.equals(p)&&plugin.mentions().enabled(target)&&lower.contains("@"+target.getName().toLowerCase(Locale.ROOT))){target.playSound(target.getLocation(),Sound.BLOCK_NOTE_BLOCK_PLING,1f,1.5f);target.sendActionBar(Component.text("✦ You were mentioned by "+p.getName()+" ✦",NamedTextColor.GOLD));}}

    @EventHandler public void onInventoryClick(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p))return;String title=e.getView().getTitle();if(title.equals("✦ YETIBOXXED PRESETS ✦")){e.setCancelled(true);if(e.getRawSlot()==13&&!plugin.presets().owns(p.getUniqueId())){if(plugin.presets().buy(p)){p.closeInventory();plugin.presets().enter(p,p.getUniqueId());}else p.sendMessage(Msg.error("You need "+plugin.presets().purchaseCost()+" ❄."));}else if(e.getRawSlot()==10&&plugin.presets().owns(p.getUniqueId())){p.closeInventory();plugin.presets().enter(p,p.getUniqueId());}else if(e.getRawSlot()==12&&plugin.presets().owns(p.getUniqueId()))plugin.menus().upgrades(p);}
        if(title.equals("✦ PLOT UPGRADES ✦")){e.setCancelled(true);if(e.getRawSlot()==13){if(plugin.presets().upgrade(p)){p.sendMessage(Msg.gold("Preset upgraded to level "+plugin.presets().level(p.getUniqueId())+"."));plugin.menus().upgrades(p);}else p.sendMessage(Msg.error("Upgrade unavailable or insufficient Yeti Coins."));}}
        if(title.equals("✦ YETIBOXXED SHOP ✦")){e.setCancelled(true);if(e.getCurrentItem()==null||e.getCurrentItem().getType().isAir())return;String id=plugin.customItems().id(e.getCurrentItem());if(id==null)return;if(plugin.shop().owns(p,id)){if(!plugin.presets().insideOwn(p)){p.sendMessage(Msg.error("Enter your own Preset to take out custom items."));return;}p.getInventory().addItem(plugin.customItems().create(id));p.sendMessage(Msg.gold("Custom item added to your Preset inventory."));}else if(plugin.shop().buy(p,id)){p.sendMessage(Msg.gold("Permanent unlock purchased: "+id+"."));}else p.sendMessage(Msg.error("You don't have enough Yeti Coins, or you already own it."));}
        if(title.equals("✦ YETIPL COSMETICS ✦")){e.setCancelled(true);String cosmetic=plugin.cosmetics().idForSlot(e.getRawSlot());if(cosmetic!=null){if(plugin.cosmetics().owns(p,cosmetic)){plugin.cosmetics().equip(p,cosmetic);p.sendMessage(Msg.gold("Cosmetic equipped: "+cosmetic));}else if(plugin.cosmetics().buy(p,cosmetic)){plugin.cosmetics().equip(p,cosmetic);p.sendMessage(Msg.gold("Cosmetic purchased and equipped."));}else p.sendMessage(Msg.error("Not enough Yeti Coins."));}}
        if(title.equals("✦ YetiPL Potion Maker ✦")){e.setCancelled(true);ItemStack out=switch(e.getRawSlot()){case 10->plugin.potions().speed();case 12->plugin.potions().strength();case 14->plugin.potions().rush();case 16->plugin.potions().arrow();default->null;};if(out!=null){p.getInventory().addItem(out);p.sendMessage(Msg.gold("Custom potion created."));}}}

    @EventHandler public void onInventoryClose(InventoryCloseEvent e){if(e.getPlayer() instanceof Player p&&plugin.vaults().isVault(p,e.getView().getTitle()))plugin.vaults().save(p,e.getInventory());}

    @EventHandler public void onCommandPre(PlayerCommandPreprocessEvent e){String raw=e.getMessage(); if(raw.toLowerCase(Locale.ROOT).startsWith("//set ")){e.setCancelled(true);Material m=Material.matchMaterial(raw.substring(6).trim());int n=m==null?-3:plugin.worldEdit().set(e.getPlayer(),m);e.getPlayer().sendMessage(n>=0?Msg.gold("Set "+n+" blocks."):Msg.error(n==-2?"Selection exceeds the WorldEdit safety limit.":"Invalid or incomplete selection."));return;}if(raw.toLowerCase(Locale.ROOT).startsWith("//replace ")){e.setCancelled(true);String[] x=raw.substring(10).trim().split("\\s+");if(x.length>=2){Material f=Material.matchMaterial(x[0]),t=Material.matchMaterial(x[1]);int n=f==null||t==null?-3:plugin.worldEdit().replace(e.getPlayer(),f,t);e.getPlayer().sendMessage(n>=0?Msg.gold("Replaced "+n+" blocks."):Msg.error("Invalid materials, selection, or safety limit."));}return;}if(raw.equalsIgnoreCase("//copy")){e.setCancelled(true);int n=plugin.worldEdit().copy(e.getPlayer());e.getPlayer().sendMessage(n>=0?Msg.gold("Copied "+n+" blocks."):Msg.error("Select a valid region first."));return;}if(raw.equalsIgnoreCase("//paste")){e.setCancelled(true);int n=plugin.worldEdit().paste(e.getPlayer());e.getPlayer().sendMessage(n>=0?Msg.gold("Pasted "+n+" blocks."):Msg.error("Clipboard is empty."));return;}if(raw.equalsIgnoreCase("//undo")){e.setCancelled(true);e.getPlayer().sendMessage(Msg.gold("Undid "+plugin.worldEdit().undo(e.getPlayer())+" blocks."));return;}if(raw.equalsIgnoreCase("//redo")){e.setCancelled(true);e.getPlayer().sendMessage(Msg.gold("Redid "+plugin.worldEdit().redo(e.getPlayer())+" blocks."));return;}if(e.getMessage().equalsIgnoreCase("//wand")){e.setCancelled(true);e.getPlayer().getInventory().addItem(plugin.wand());e.getPlayer().sendMessage(Msg.gold("YetiPL Golden Selection Wand received."));}if(plugin.moderation().frozen(e.getPlayer().getUniqueId())&&!e.getPlayer().hasPermission("yetipl.freeze.bypass")){String cmd=e.getMessage().toLowerCase(Locale.ROOT);if(!cmd.startsWith("/msg ")&&!cmd.startsWith("/tell ")&&!cmd.startsWith("/r ")){e.setCancelled(true);e.getPlayer().sendMessage(Msg.error("You are frozen. Follow staff instructions."));}}}

    @EventHandler public void onDrop(PlayerDropItemEvent e){if(plugin.moderation().frozen(e.getPlayer().getUniqueId()))e.setCancelled(true);if(e.getPlayer().getWorld()==plugin.presets().world()&&plugin.presets().insideOwn(e.getPlayer())){/* drops remain inside preset world only */}}
    @EventHandler public void onHeld(PlayerItemHeldEvent e){Bukkit.getScheduler().runTaskLater(plugin,()->plugin.itemDisguises().refresh(e.getPlayer()),1L);}

    @EventHandler public void onAdvancement(PlayerAdvancementDoneEvent e){if(e.getPlayer().getWorld()!=plugin.presets().world()||advancing.contains(e.getPlayer().getUniqueId()))return;advancing.add(e.getPlayer().getUniqueId());try{var progress=e.getPlayer().getAdvancementProgress(e.getAdvancement());for(String criterion:new HashSet<>(progress.getAwardedCriteria()))progress.revokeCriteria(criterion);}finally{advancing.remove(e.getPlayer().getUniqueId());}}

    @EventHandler public void onResourcePack(PlayerResourcePackStatusEvent e){String n=e.getStatus().name();if((n.contains("DECLINED")||n.contains("FAILED"))&&plugin.getConfig().getBoolean("resource-pack.required",false))e.getPlayer().kick(Component.text("✦ YetiPL ✦ The YetisBOXXED resource pack is required to join.",NamedTextColor.RED));}
}
