package gg.yetisboxxed.yetipl.command;

import gg.yetisboxxed.yetipl.YetiPLPlugin;
import gg.yetisboxxed.yetipl.service.BanService;
import gg.yetisboxxed.yetipl.service.ChatFilterService;
import gg.yetisboxxed.yetipl.util.Msg;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.command.*;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.event.inventory.InventoryType;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.SkullMeta;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.lang.reflect.Method;
import java.util.*;

public final class FeatureCommand implements CommandExecutor, TabCompleter {
    private final YetiPLPlugin pl;
    public FeatureCommand(YetiPLPlugin plugin){this.pl=plugin;}
    @Override public boolean onCommand(@NotNull CommandSender sender,@NotNull Command command,@NotNull String label,@NotNull String[] args){String c=command.getName().toLowerCase(Locale.ROOT);try{return route(sender,c,args);}catch(Throwable t){String id=pl.errors().report("command:"+c,t);sender.sendMessage(Msg.error("That command failed safely. Error ID: "+id));return true;}}
    private boolean route(CommandSender s,String c,String[] a){return switch(c){
        case "wand"->wand(s);case "setwarp"->setWarp(s,a);case "warp"->warp(s,a);case "warps"->warps(s);case "delwarp"->delWarp(s,a);
        case "preset"->preset(s,a);case "upgrades"->upgrades(s);case "yeticoins"->coins(s,a);case "shop"->shop(s,a);case "customitems"->shop(s,new String[]{"customitems"});
        case "crate"->crate(s,a);case "bindcrate"->bindCrate(s,a);case "bindcratekey"->bindCrateKey(s,a);case "gen"->gen(s,a);case "arch"->arch(s,a);
        case "rg"->region(s,a);case "portal"->portal(s,a);case "potionmaker"->potions(s);case "holo"->holo(s,a);case "rules"->rules(s);case "discord"->discord(s,a);
        case "chatfilter"->chatFilter(s,a);case "chatcooldown"->chatCooldown(s,a);case "chatcolor"->chatColor(s,a);case "prefix"->prefix(s,a);case "affix"->affix(s,a);case "rank"->rank(s,a);
        case "bugs"->bugs(s,a);case "seebugs"->seeBugs(s,a);case "itemdisguise"->itemDisguise(s,a);case "disguise"->disguise(s,a);
        case "ban"->ban(s,a,false);case "banip"->ban(s,a,true);case "banlist"->banList(s);case "vanish"->vanish(s);case "spectate"->spectate(s,a);case "freeze"->freeze(s,a);
        case "anvil","craft","grindstone","smith","blastfurnace","smoker"->workstation(s,c);case "workstation"->workstation(s,a.length>0?a[0]:"");
        case "head"->head(s,a);case "enchant"->enchant(s,a);case "ride"->ride(s,a);case "trim"->trim(s,a);case "commands"->commands(s);
        case "vault","pv"->vault(s,a);case "enderchest","ec"->ender(s,a);case "shopkeeper"->shopkeeper(s,a);case "disc"->disc(s,a);case "nakedkilling"->naked(s);case "yac"->yac(s,a);case "nbt"->nbt(s,a);case "lpgui"->lpgui(s,a);case "mentions"->mentions(s,a);case "chatgames"->chatgames(s,a);
        default->false;};}
    private Player player(CommandSender s){if(s instanceof Player p)return p;s.sendMessage("Players only.");return null;}
    private boolean wand(CommandSender s){Player p=player(s);if(p==null)return true;p.getInventory().addItem(pl.wand());p.sendMessage(Msg.gold("YetiPL Golden Selection Wand received."));return true;}
    private boolean setWarp(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length<1){p.sendMessage(Msg.error("/setwarp <name>"));return true;}pl.warps().set(a[0],p.getLocation());p.sendMessage(Msg.gold("Warp set: "+a[0]));return true;}
    private boolean warp(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length<1){p.sendMessage(Msg.error("/warp <name>"));return true;}var l=pl.warps().get(a[0]);if(l==null)p.sendMessage(Msg.error("Unknown warp."));else p.teleport(l);return true;}
    private boolean warps(CommandSender s){s.sendMessage(Msg.gold("Warps: "+String.join(", ",pl.warps().names())));return true;}
    private boolean delWarp(CommandSender s,String[] a){if(a.length<1)return true;pl.warps().delete(a[0]);s.sendMessage(Msg.gold("Warp removed."));return true;}
    private boolean preset(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length==0){pl.menus().preset(p);return true;}switch(a[0].toLowerCase()){case "buy","create"->{if(pl.presets().buy(p)){p.sendMessage(Msg.gold("Preset purchased!"));pl.presets().enter(p,p.getUniqueId());}else p.sendMessage(Msg.error("You already own a Preset or need "+pl.presets().purchaseCost()+" ❄."));}case "home"->{if(!pl.presets().owns(p.getUniqueId()))p.sendMessage(Msg.error("You need a Preset first."));else pl.presets().enter(p,p.getUniqueId());}case "leave"->pl.presets().leave(p);case "visit"->{if(a.length<2){p.sendMessage(Msg.error("/preset visit <player>"));break;}OfflinePlayer o=Bukkit.getOfflinePlayer(a[1]);if(!pl.presets().owns(o.getUniqueId()))p.sendMessage(Msg.error("That player has no Preset."));else if(!pl.presets().canVisit(p,o.getUniqueId()))p.sendMessage(Msg.error("You are not trusted to visit."));else pl.presets().enter(p,o.getUniqueId());}case "trust","untrust","hypertrust","unhypertrust"->{if(a.length<2||!pl.presets().owns(p.getUniqueId())){p.sendMessage(Msg.error("You need your own Preset and a player name."));break;}OfflinePlayer o=Bukkit.getOfflinePlayer(a[1]);boolean hyper=a[0].toLowerCase().contains("hyper");if(hyper&&!pl.presets().owns(o.getUniqueId())){p.sendMessage(Msg.error("Players must own a Preset before they can be hyper-trusted."));break;}if(a[0].toLowerCase().startsWith("un"))pl.presets().untrust(p.getUniqueId(),o.getUniqueId(),hyper);else pl.presets().trust(p.getUniqueId(),o.getUniqueId(),hyper);p.sendMessage(Msg.gold("Preset access updated for "+o.getName()+"."));}case "reset"->{if(a.length<2||!a[1].equalsIgnoreCase("confirm")){p.sendMessage(Msg.error("This erases the build but keeps ownership/upgrades. Use /preset reset confirm"));break;}pl.presets().reset(p.getUniqueId());p.sendMessage(Msg.gold("Preset reset."));}case "public"->{boolean on=a.length>1&&a[1].equalsIgnoreCase("on");pl.presets().setPublic(p.getUniqueId(),on);p.sendMessage(Msg.gold("Public visiting: "+on));}case "upgrades"->pl.menus().upgrades(p);case "info"->p.sendMessage(Msg.gold("Level "+pl.presets().level(p.getUniqueId())+"/10 • Border "+pl.presets().size(p.getUniqueId())+"×"+pl.presets().size(p.getUniqueId())));default->p.sendMessage(Msg.error("/preset <buy|home|visit|trust|hypertrust|reset|upgrades|leave>"));}return true;}
    private boolean upgrades(CommandSender s){Player p=player(s);if(p==null)return true;pl.menus().upgrades(p);return true;}
    private boolean coins(CommandSender s,String[] a){Player p=s instanceof Player x?x:null;if(a.length==0||a[0].equalsIgnoreCase("balance")){if(p==null){s.sendMessage("/yeticoins <give|take|set|history>");return true;}s.sendMessage(Msg.gold("Yeti Coins: "+(pl.coins().infinite(p)?"∞":pl.coins().balance(p.getUniqueId()))+" ❄"));return true;}if(a[0].equalsIgnoreCase("shop")){if(p!=null)pl.menus().shop(p);return true;}if(a[0].equalsIgnoreCase("history")&&a.length>1){OfflinePlayer o=Bukkit.getOfflinePlayer(a[1]);s.sendMessage(Msg.gold("Recent Yeti Coin history for "+a[1]+":"));pl.coins().history(o.getUniqueId()).stream().limit(10).forEach(s::sendMessage);return true;}if((a[0].equalsIgnoreCase("give")||a[0].equalsIgnoreCase("take")||a[0].equalsIgnoreCase("set"))&&a.length>=3&&s.hasPermission("yetipl.yeticoins.admin")){OfflinePlayer o=Bukkit.getOfflinePlayer(a[1]);long n;try{n=Long.parseLong(a[2]);}catch(Exception e){s.sendMessage(Msg.error("Invalid amount."));return true;}if(a[0].equalsIgnoreCase("give"))pl.coins().add(o.getUniqueId(),n,"admin:"+s.getName());else if(a[0].equalsIgnoreCase("take"))pl.coins().take(o.getUniqueId(),n,"admin:"+s.getName());else pl.coins().set(o.getUniqueId(),n,"admin:"+s.getName());s.sendMessage(Msg.gold("Balance updated."));return true;}return true;}
    private boolean shop(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length>0&&a[0].equalsIgnoreCase("cosmetics"))pl.cosmetics().open(p);else pl.menus().shop(p);return true;}
    private boolean crate(CommandSender s,String[] a){Player p=s instanceof Player x?x:null;if(a.length<1){s.sendMessage(Msg.gold("Crates: "+String.join(", ",pl.crates().names())));return true;}switch(a[0].toLowerCase()){case "create"->{if(a.length>1){pl.crates().create(a[1]);s.sendMessage(Msg.gold("Crate created."));}}case "addreward"->{if(p!=null&&a.length>1&&!p.getInventory().getItemInMainHand().getType().isAir()){pl.crates().addReward(a[1],p.getInventory().getItemInMainHand());p.sendMessage(Msg.gold("Held item added as a reward."));}}case "givekey"->{if(a.length>=4){Player t=Bukkit.getPlayer(a[1]);ItemStack key=pl.crates().key(a[2]);if(t!=null&&key!=null){int n=Integer.parseInt(a[3]);key=key.clone();key.setAmount(Math.max(1,Math.min(64,n)));t.getInventory().addItem(key);}}}default->s.sendMessage(Msg.gold("/crate <create|addreward|givekey>"));}return true;}
    private boolean bindCrate(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length<1){p.sendMessage(Msg.error("/bindcrate <crate>"));return true;}Block b=p.getTargetBlockExact(6);if(b==null){p.sendMessage(Msg.error("Look at the block you want to bind."));return true;}pl.crates().bind(a[0],b.getLocation());p.sendMessage(Msg.gold("Bound "+a[0]+" to "+b.getType()+"."));return true;}
    private boolean bindCrateKey(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;String name=a.length>0?a[0]:null;if(name==null){Block b=p.getTargetBlockExact(6);if(b!=null)name=pl.crates().at(b.getLocation());}if(name==null||p.getInventory().getItemInMainHand().getType().isAir()){p.sendMessage(Msg.error("Hold the key item and use /bindcratekey <crate>."));return true;}pl.crates().bindKey(name,p.getInventory().getItemInMainHand().clone());p.sendMessage(Msg.gold("Key bound to "+name+"."));return true;}
    private boolean gen(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length<1){p.sendMessage(Msg.gold("Gens: "+String.join(", ",pl.gens().names())));return true;}switch(a[0].toLowerCase()){case "create"->{if(a.length<2)return true;var sel=pl.selections().get(p);if(!sel.complete()){p.sendMessage(Msg.error("Select two corners with the Golden Axe."));break;}pl.gens().create(a[1],sel);p.sendMessage(Msg.gold("Gen created."));}case "settime"->{if(a.length<3)return true;pl.gens().setDelay(a[1],parseTicks(a[2]));p.sendMessage(Msg.gold("Regeneration timer updated."));}case "addblock"->{if(a.length<3)return true;Material m=Material.matchMaterial(a[2]);if(m!=null)pl.gens().addBlock(a[1],m);p.sendMessage(Msg.gold("Block added to generator pool."));}default->p.sendMessage(Msg.gold("/gen <create|settime|addblock>"));}return true;}
    private boolean arch(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length<1){p.sendMessage(Msg.gold("Archaeology regions: "+String.join(", ",pl.archaeology().names())));return true;}if(a[0].equalsIgnoreCase("create")&&a.length>1){var sel=pl.selections().get(p);if(!sel.complete()){p.sendMessage(Msg.error("Select a region first."));return true;}pl.archaeology().create(a[1],sel);p.sendMessage(Msg.gold("Archaeology region created."));}else if(a[0].equalsIgnoreCase("addreward")&&a.length>1&&!p.getInventory().getItemInMainHand().getType().isAir()){pl.archaeology().addReward(a[1],p.getInventory().getItemInMainHand());p.sendMessage(Msg.gold("Brush reward added."));}return true;}
    private boolean region(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length<1){p.sendMessage(Msg.gold("Regions: "+String.join(", ",pl.regions().names())));return true;}switch(a[0].toLowerCase()){case "create"->{if(a.length<2)return true;var sel=pl.selections().get(p);if(!sel.complete()){p.sendMessage(Msg.error("Select a region first."));break;}pl.regions().create(a[1],sel);p.sendMessage(Msg.gold("Region created."));}case "delete"->{if(a.length>1)pl.regions().delete(a[1]);}case "flag"->{if(a.length<4){p.sendMessage(Msg.error("/rg flag <region> <flag> <allow|deny>"));break;}if(a[2].equalsIgnoreCase("blockedhand")||a[2].equalsIgnoreCase("requirehand")){if(a.length<5)break;Material m=Material.matchMaterial(a[4]);if(m!=null)pl.regions().listMaterial(a[1],a[2].toLowerCase(),m,a[3].equalsIgnoreCase("add"));}else pl.regions().flag(a[1],a[2].toLowerCase(),a[3].equalsIgnoreCase("allow"));p.sendMessage(Msg.gold("Region flag updated."));}default->p.sendMessage(Msg.gold("/rg <create|delete|flag>"));}return true;}
    private boolean portal(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length>=2&&a[0].equalsIgnoreCase("create")){var sel=pl.selections().get(p);if(!sel.complete()){p.sendMessage(Msg.error("Select two portal corners first."));return true;}pl.portals().create(a[1],sel,p.getLocation());p.sendMessage(Msg.gold("Portal created; destination is your current location."));}else p.sendMessage(Msg.gold("/portal create <name>"));return true;}
    private boolean potions(CommandSender s){Player p=player(s);if(p!=null)pl.potions().open(p);return true;}
    private boolean holo(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length>=3&&a[0].equalsIgnoreCase("create")){pl.holograms().create(a[1],p.getLocation(),String.join(" ",Arrays.copyOfRange(a,2,a.length)));p.sendMessage(Msg.gold("Hologram created."));}else if(a.length>=2&&a[0].equalsIgnoreCase("delete")){pl.holograms().delete(a[1]);p.sendMessage(Msg.gold("Hologram deleted."));}else p.sendMessage(Msg.gold("Holograms: "+String.join(", ",pl.holograms().names())));return true;}
    private boolean rules(CommandSender s){s.sendMessage(Component.text("✦ YETIBOXXED RULES ✦",NamedTextColor.GOLD));int n=1;for(String r:pl.rules().rules())s.sendMessage(Component.text((n++)+". "+r,NamedTextColor.YELLOW));return true;}
    private boolean discord(CommandSender s,String[] a){s.sendMessage(Component.text("✦ YETIBOXXED DISCORD ✦ ",NamedTextColor.GOLD).append(Component.text(pl.rules().discord(),NamedTextColor.YELLOW)));return true;}
    private boolean chatFilter(CommandSender s,String[] a){if(a.length==0){s.sendMessage(Msg.gold("Chat filter: "+(pl.chatFilter().enabled()?"ON":"OFF")));return true;}switch(a[0].toLowerCase()){case "toggle"->pl.chatFilter().enabled(!pl.chatFilter().enabled());case "add"->{if(a.length>=2)pl.chatFilter().add(a[1],ChatFilterService.Action.BLOCK,"****");}case "remove"->{if(a.length>=2)pl.chatFilter().remove(a[1]);}case "action"->{if(a.length>=3){try{pl.chatFilter().add(a[1],ChatFilterService.Action.valueOf(a[2].toUpperCase()),a.length>3?a[3]:"****");}catch(Exception ignored){}}}default->{}}s.sendMessage(Msg.gold("Chat filter updated."));return true;}
    private boolean chatCooldown(CommandSender s,String[] a){if(a.length>=3&&a[0].equalsIgnoreCase("set")){try{pl.ranks().cooldown(a[1],Double.parseDouble(a[2]));s.sendMessage(Msg.gold("Cooldown updated."));}catch(Exception e){s.sendMessage(Msg.error("Use a number of seconds, decimals allowed."));}}return true;}
    private boolean chatColor(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length>=2&&a[0].equalsIgnoreCase("set")){pl.ranks().chatColor(pl.ranks().rank(p.getUniqueId()),a[1]);p.sendMessage(Msg.gold("Rank chat color updated."));}else p.sendMessage(Msg.gold("Use /chatcolor set <MiniMessage color>"));return true;}
    private boolean prefix(CommandSender s,String[] a){if(a.length>=3&&a[0].equalsIgnoreCase("set")){pl.ranks().prefix(a[1],String.join(" ",Arrays.copyOfRange(a,2,a.length)));s.sendMessage(Msg.gold("Prefix updated exactly as entered; no brackets added."));}return true;}
    private boolean affix(CommandSender s,String[] a){if(a.length>=3&&a[0].equalsIgnoreCase("setprefix"))pl.ranks().prefix(a[1],String.join(" ",Arrays.copyOfRange(a,2,a.length)));else if(a.length>=3&&a[0].equalsIgnoreCase("setsuffix"))pl.ranks().suffix(a[1],String.join(" ",Arrays.copyOfRange(a,2,a.length)));else s.sendMessage(Msg.gold("/affix <setprefix|setsuffix> <rank> <text>"));return true;}
    private boolean rank(CommandSender s,String[] a){if(a.length>=3&&a[0].equalsIgnoreCase("set")){OfflinePlayer o=Bukkit.getOfflinePlayer(a[1]);pl.ranks().rank(o.getUniqueId(),a[2]);s.sendMessage(Msg.gold("Rank set to "+a[2]+"."));}else s.sendMessage(Msg.gold("Rank presets: "+String.join(", ",pl.ranks().presets())));return true;}
    private boolean bugs(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length==0){p.sendMessage(Msg.error("/bugs <description>"));return true;}int id=pl.bugs().submit(p,String.join(" ",a));p.sendMessage(Msg.gold("Bug report #"+id+" submitted. Thank you!"));return true;}
    private boolean seeBugs(CommandSender s,String[] a){if(a.length>=3&&a[0].equalsIgnoreCase("status")){pl.bugs().status(a[1],a[2].toUpperCase());return true;}s.sendMessage(Msg.gold("Bug reports:"));pl.bugs().ids().stream().sorted().limit(30).forEach(id->s.sendMessage(pl.bugs().summary(id)));return true;}
    private boolean itemDisguise(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length==0){Material m=pl.itemDisguises().get(p);p.sendMessage(Msg.gold("Held-item disguise: "+(m==null?"OFF":m.name())));return true;}if(a[0].equalsIgnoreCase("reset")){pl.itemDisguises().reset(p);p.sendMessage(Msg.gold("Item disguise removed."));return true;}Material m=Material.matchMaterial(a[0]);if(m==null){p.sendMessage(Msg.error("Unknown item."));return true;}pl.itemDisguises().set(p,m);p.sendMessage(Msg.gold("Held item now appears as "+m+" to other players."));return true;}
    private boolean disguise(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length>0&&a[0].equalsIgnoreCase("enchant")){ItemStack i=p.getInventory().getItemInMainHand();if(i.getType().isAir())return true;try{Method m=i.getItemMeta().getClass().getMethod("setEnchantmentGlintOverride",Boolean.class);var meta=i.getItemMeta();m.invoke(meta,Boolean.TRUE);i.setItemMeta(meta);p.sendMessage(Msg.gold("Cosmetic enchant glow enabled."));}catch(Exception e){p.sendMessage(Msg.error("Glint override is unavailable on this server build."));}}return true;}
    private boolean ban(CommandSender s,String[] a,boolean ip){if(a.length<3){s.sendMessage(Msg.error("/"+(ip?"banip":"ban")+" <player|ip> <duration> <reason>"));return true;}long ms=BanService.parse(a[1]);if(ms<0){s.sendMessage(Msg.error("Duration required: 30m, 2h, 7d, 1w. Permanent bans are disabled."));return true;}String reason=String.join(" ",Arrays.copyOfRange(a,2,a.length));if(ip){String target=a[0];Player online=Bukkit.getPlayer(a[0]);if(online!=null)target=online.getAddress().getAddress().getHostAddress();pl.bans().banIp(target,ms,reason,s.getName());if(online!=null)online.kick(Component.text("Temporarily IP banned: "+reason,NamedTextColor.RED));}else{OfflinePlayer o=Bukkit.getOfflinePlayer(a[0]);pl.bans().ban(o.getUniqueId(),o.getName()==null?a[0]:o.getName(),ms,reason,s.getName());Player online=o.getPlayer();if(online!=null)online.kick(Component.text("Temporarily banned: "+reason,NamedTextColor.RED));}s.sendMessage(Msg.gold("Temporary ban created."));return true;}
    private boolean banList(CommandSender s){s.sendMessage(Msg.gold("Active temporary bans:"));pl.bans().list().forEach(s::sendMessage);return true;}
    private boolean vanish(CommandSender s){Player p=player(s);if(p!=null)p.sendMessage(Msg.gold("Vanish: "+(pl.moderation().toggleVanish(p)?"ON":"OFF")));return true;}
    private boolean spectate(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length==0||a[0].equalsIgnoreCase("stop")){pl.moderation().stopSpectate(p);p.sendMessage(Msg.gold("Spectate stopped."));}else{Player t=Bukkit.getPlayer(a[0]);if(t!=null){pl.moderation().spectate(p,t);p.sendMessage(Msg.gold("Spectating "+t.getName()+"."));}}return true;}
    private boolean freeze(CommandSender s,String[] a){if(a.length<1)return true;Player t=Bukkit.getPlayer(a[0]);if(t==null)return true;boolean on=pl.moderation().toggleFreeze(t);t.sendTitle(on?"§cYOU ARE FROZEN":"§aUNFROZEN",on?"§eDo not disconnect. Follow staff instructions.":"§eYou may continue playing.",5,60,10);s.sendMessage(Msg.gold(t.getName()+" frozen: "+on));return true;}
    private boolean workstation(CommandSender s,String kind){Player p=player(s);if(p==null)return true;switch(kind.toLowerCase()){case "craft"->p.openWorkbench(null,true);case "anvil"->p.openAnvil(null,true);case "grindstone"->p.openGrindstone(null,true);case "smith"->p.openSmithingTable(null,true);case "blastfurnace"->p.openInventory(Bukkit.createInventory(null,InventoryType.BLAST_FURNACE,"Portable Blast Furnace"));case "smoker"->p.openInventory(Bukkit.createInventory(null,InventoryType.SMOKER,"Portable Smoker"));default->p.sendMessage(Msg.error("Unknown workstation."));}return true;}
    private boolean head(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;String name=a.length>0?a[0]:p.getName();ItemStack h=new ItemStack(Material.PLAYER_HEAD);SkullMeta m=(SkullMeta)h.getItemMeta();m.setOwningPlayer(Bukkit.getOfflinePlayer(name));h.setItemMeta(m);p.getInventory().addItem(h);return true;}
    private boolean enchant(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length<2)return true;NamespacedKey k=NamespacedKey.minecraft(a[0].toLowerCase());Enchantment ench=Registry.ENCHANTMENT.get(k);if(ench==null){p.sendMessage(Msg.error("Unknown enchantment."));return true;}int level;try{level=Math.max(1,Math.min(255,Integer.parseInt(a[1])));}catch(NumberFormatException ex){p.sendMessage(Msg.error("Level must be a whole number from 1 to 255."));return true;}p.getInventory().getItemInMainHand().addUnsafeEnchantment(ench,level);p.sendMessage(Msg.gold("Applied "+a[0]+" "+level+"."));return true;}
    private boolean ride(CommandSender s,String[] a){Player p=player(s);if(p==null||a.length<1)return true;Player t=Bukkit.getPlayer(a[0]);if(t!=null)t.addPassenger(p);return true;}
    private boolean trim(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length>=2&&a[0].equalsIgnoreCase("get")){ItemStack i=pl.trims().template(a[1]);if(i!=null)p.getInventory().addItem(i);else p.sendMessage(Msg.error("Unknown custom trim. Options: "+String.join(", ",pl.trims().custom())));}else p.sendMessage(Msg.gold("/trim get <"+String.join("|",pl.trims().custom())+">"));return true;}
    private boolean commands(CommandSender s){Player p=player(s);if(p!=null)pl.menus().commands(p);return true;}
    private boolean vault(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;int n=1;if(a.length>0)try{n=Integer.parseInt(a[0]);}catch(Exception ignored){}pl.vaults().open(p,n);return true;}
    private boolean ender(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;Player target=p;if(a.length>0&&p.hasPermission("yetipl.enderchest.others")){Player t=Bukkit.getPlayer(a[0]);if(t!=null)target=t;}p.openInventory(target.getEnderChest());return true;}
    private boolean shopkeeper(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length>=2&&a[0].equalsIgnoreCase("create")){pl.shopkeepers().create(a[1],p.getLocation());p.sendMessage(Msg.gold("Shopkeeper created."));}else p.sendMessage(Msg.gold("Shopkeepers: "+String.join(", ",pl.shopkeepers().names())));return true;}
    private boolean disc(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length>=4&&a[0].equalsIgnoreCase("create")){pl.discs().create(a[1],a[2],a[3]);p.sendMessage(Msg.gold("Disc configured. The YouTube URL is a source reference; playable audio must be in the required resource pack as sound key "+a[3]+"."));}else if(a.length>=2&&a[0].equalsIgnoreCase("give")){ItemStack i=pl.discs().item(a[1]);if(i!=null)p.getInventory().addItem(i);}else p.sendMessage(Msg.gold("/disc <create name youtubeUrl soundKey|give name>"));return true;}
    private boolean naked(CommandSender s){boolean v=!pl.getConfig().getBoolean("pvp.allow-naked-killing",false);pl.getConfig().set("pvp.allow-naked-killing",v);pl.saveConfig();s.sendMessage(Msg.gold("Naked killing allowed: "+v));return true;}
    private boolean yac(CommandSender s,String[] a){s.sendMessage(Msg.gold("YetiPL AntiCheat: attack timing protection active • Lag stage: "+pl.lagProtector().level()));return true;}

    private boolean nbt(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;if(a.length==0){pl.itemEditor().open(p);return true;}boolean ok=false;switch(a[0].toLowerCase()){case "name"->{if(a.length>1)ok=pl.itemEditor().name(p,String.join(" ",Arrays.copyOfRange(a,1,a.length)));}case "lore"->{if(a.length>1&&a[1].equalsIgnoreCase("clear"))ok=pl.itemEditor().loreClear(p);else if(a.length>2&&a[1].equalsIgnoreCase("add"))ok=pl.itemEditor().loreAdd(p,String.join(" ",Arrays.copyOfRange(a,2,a.length)));}case "glint"->ok=pl.itemEditor().glint(p);case "data"->{if(a.length>=3)ok=pl.itemEditor().data(p,a[1],String.join(" ",Arrays.copyOfRange(a,2,a.length)));}}p.sendMessage(ok?Msg.gold("Held item updated."):Msg.error("Could not update the held item."));return true;}
    private boolean lpgui(CommandSender s,String[] a){Player p=player(s);if(a.length==0){if(p!=null)pl.permissionsBridge().open(p);return true;}if(a.length>=4&&(a[0].equalsIgnoreCase("user")||a[0].equalsIgnoreCase("group"))){boolean value=Boolean.parseBoolean(a[3]);boolean ok=pl.permissionsBridge().set(a[0].toLowerCase(),a[1],a[2],value);s.sendMessage(ok?Msg.gold("LuckPerms permission updated."):Msg.error("LuckPerms is not available or rejected the command."));}else s.sendMessage(Msg.error("/lpgui <user|group> <target> <permission> <true|false>"));return true;}
    private boolean mentions(CommandSender s,String[] a){Player p=player(s);if(p==null)return true;boolean value=a.length==0?!pl.mentions().enabled(p):a[0].equalsIgnoreCase("on");pl.mentions().enabled(p,value);p.sendMessage(Msg.gold("Mentions: "+(value?"ON":"OFF")));return true;}
    private boolean chatgames(CommandSender s,String[] a){if(a.length==0){s.sendMessage(Msg.gold("/chatgames <start|stop|random>"));return true;}switch(a[0].toLowerCase()){case "start"->pl.chatGames().start();case "stop"->pl.chatGames().stop();case "random"->pl.chatGames().newGame();default->{}}s.sendMessage(Msg.gold("Chat Games updated."));return true;}
    private long parseTicks(String s){try{char u=Character.toLowerCase(s.charAt(s.length()-1));long n=Long.parseLong(s.substring(0,s.length()-1));return switch(u){case 's'->n*20;case 'm'->n*1200;case 'h'->n*72000;default->Long.parseLong(s);};}catch(Exception e){return 100;}}
    @Override public @Nullable List<String> onTabComplete(@NotNull CommandSender sender,@NotNull Command command,@NotNull String alias,@NotNull String[] args){String c=command.getName().toLowerCase(Locale.ROOT);if(c.equals("itemdisguise")&&args.length==1){List<String> out=new ArrayList<>();if("reset".startsWith(args[0].toLowerCase()))out.add("reset");Arrays.stream(Material.values()).map(m->m.name().toLowerCase()).filter(x->x.startsWith(args[0].toLowerCase())).limit(100).forEach(out::add);return out;}if(args.length==1){List<String> base=switch(c){case "preset"->List.of("buy","home","visit","trust","untrust","hypertrust","unhypertrust","reset","upgrades","info","public","leave");case "yeticoins"->List.of("balance","shop","history","give","take","set");case "crate"->List.of("create","addreward","givekey");case "gen"->List.of("create","settime","addblock");case "arch"->List.of("create","addreward");case "rg"->List.of("create","delete","flag","info","list");case "chatfilter"->List.of("toggle","add","remove","action");case "trim"->List.of("get","list");case "disc"->List.of("create","give");case "holo"->List.of("create","delete","list");default->List.of();};return base.stream().filter(x->x.startsWith(args[0].toLowerCase())).toList();}return List.of();}
}
